name: log_api
description: Log API to manage logging.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.3"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

  universal_file:
    path: ../universal_file

  mockito: ^5.4.2
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
