name: template
description: Base template for all Flutter projects.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2"
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
