name: universal_file
description: file management for different platform

version: 1.0.0+1

environment:
  sdk: ">=3.1.3"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  path_provider: ^2.1.1

  shared_preferences: ^2.2.1

  mockito: ^5.4.2
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

  build_runner: ^2.4.6

  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.6

flutter:
  uses-material-design: true
