name: Analyze and check PR
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  testing-and-analysis:
    name: Testing and Analysis
    uses: './.github/workflows/testing-and-analysis.yml'
    with:
      runs_on: 'ubuntu-latest'